const BREEDS = [
  "Labrador Retriever",
  "Golden Retriever",
  "German Shepherd",
  "Poodle",
  "Bulldog",
  "Beagle",
  "Chihuahua",
  "Dachshund",
  "Rottweiler",
  "Yorkshire Terrier",
  "Boxer",
  "Shih Tzu",
  "Pug",
  "Doberman Pinscher",
  "Siberian Husky",
  "Cocker Spaniel",
  "Schnauzer",
  "Miniature Schnauzer",
  "French Bulldog",
  "Great Dane",
  "Pembroke Welsh Corgi",
  "Boston Terrier",
  "Havanese",
  "Shetland Sheepdog",
  "Maltese",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Border Collie",
  "Pomeranian",
  "Australian Shepherd",
  "Pit Bull Terrier",
  "Cavalier King Charles Spaniel",
  "Dalmation",
  "Mixed Breed",
  "Jack Russell Terrier",
  "Chow Chow",
  "Bull Terrier",
  "Greyhound",
  "Akita",
  "Alaskan Malamute",
  "Whippet"
];

export default BREEDS;